#cloud-config
#
# SET HOSTNAME
#
hostname: oc-web-a
fqdn: oc-web-a.vcf.sddc.lab
#
# CONFIGURE NETWORK
#
write_files:
- path: /etc/netplan/50-cloud-init.yaml
  content: |
    network:
     version: 2
     ethernets:
      ens192:
       addresses: [10.1.1.18/27]
       gateway4: 10.1.1.1
       dhcp6: false
       nameservers:
         addresses:
           - 10.0.0.221
         search:
           - vcf.sddc.lab
       dhcp4: false
       optional: true
# 
#
- path: /etc/sysctl.d/60-disable-ipv6.conf
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6=1
    net.ipv6.conf.default.disable_ipv6=1
    net.ipv6.conf.lo.disable_ipv6=1
#
#
- path: /root/disable_ipv6.sh
  permissions: 0744
  owner: root
  content: |
    #!/usr/bin/env bash
    set -e
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
#
#
- path: /etc/hosts
  content: 127.0.0.1 oc-web-a
  append: true
#
#
- path: /etc/apache2/ports.conf
  content: |
    listen 8080
    listen 80
  append: true
#
#
runcmd:
- /bin/echo "BEGIN BEGIN BEGIN BEGIN BEGIN BEGIN BEGIN BEGiN BEGIN"
- /bin/echo "BEGIN BEGIN BEGIN BEGIN BEGIN BEGIN BEGIN BEGiN BEGIN"
- bash /root/disable_ipv6.sh
- /usr/sbin/netplan apply
- /sbin/sysctl -w net.ipv6.conf.all.disable_ipv6=1
- /sbin/sysctl -w net.ipv6.conf.default.disable_ipv6=1
- /sbin/sysctl -w net.ipv6.conf.lo.disable_ipv6=1
- /usr/bin/apt-get -y clean
- /usr/bin/apt-get -y autoremove --purge
- /bin/systemctl restart apache2
- export USER="ocuser"
- export PASS="VMware123!"
- /bin/echo $USER:$PASS | /usr/sbin/chpasswd
- /bin/sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
- /usr/sbin/service ssh reload
- /usr/bin/git clone https://github.com/jsenicka/opencart-demo.git /tmp/opencart
- /bin/sleep 30
- /bin/mv /tmp/opencart /var/www/
- /bin/mv /var/www/opencart/catalog/controller/startup/startup.php  /var/www/opencart/catalog/controller/startup/startup.php.orig
- /bin/mv /var/www/opencart/oc-startup.php /var/www/opencart/catalog/controller/startup/startup.php
- /bin/chown -R www-data.www-data /var/www/opencart
- /bin/chmod -R 775 /var/www/opencart
- /usr/bin/tee /etc/apache2/sites-available/opencart.conf > /dev/null << EOF
- <VirtualHost *:80>
-   ServerName www.opencart.vcf.sddc.lab
-   DocumentRoot /var/www/opencart
-   <Directory /var/www/opencart/>
-     AllowOverride All
-     allow from all
-   </Directory>
- </VirtualHost>
- <VirtualHost *:8080>
-   ServerName www.opencart.vcf.sddc.lab
-   DocumentRoot /var/www/opencart
-   <Directory /var/www/opencart/>
-     AllowOverride All
-     allow from all
-   </Directory>
- </VirtualHost>
- EOF
- cd /etc/apache2/sites-available/
- /usr/sbin/a2ensite opencart.conf
- /usr/sbin/a2dissite 000-default.conf
- /bin/systemctl reload apache2
- /bin/systemctl restart apache2
- /bin/echo "[client]" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- /bin/echo "user=ocuser" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- /bin/echo "password=$PASS" >> /etc/mysql/mysql.conf.d/mysqld.cnf
- MySQLip=10.1.1.50
- OC-Apache-A-ip=10.1.1.18
- export MySQLip="10.1.1.50"
- export OCApacheip="10.1.1.18"
- /bin/sed -i "s/MOAD Electronic Super Store/Holodeck SDN Lab OC-Apache/g" /var/www/opencart/install/opencart.sql
- /usr/bin/mysql -u $USER -h $MySQLip -e 'source /var/www/opencart/install/opencart.sql'
- /usr/bin/mysql -u $USER -h $MySQLip -e "INSERT INTO oc_user (user_id,user_group_id,username,password,salt,firstname,lastname,email,image,code,ip,status,date_added) VALUES (1,1,'admin','5feaa046f6927df3d744007ec1491dba838f672e','c4wnfrq9J','demo','user','admin@admin.com','none','none','none',1,'2019-01-31 06:29:09')" opencart
- /bin/sed -i "s/frontendiphere/$OCApacheip/g" /var/www/opencart/config.php
- /bin/sed -i "s/dbiphere/$MySQLip/g" /var/www/opencart/config.php
- /bin/sed -i "s/usernamehere/$USER/g" /var/www/opencart/config.php
- /bin/sed -i "s/passwordhere/$PASS/g" /var/www/opencart/config.php
- /bin/sed -i "s/frontendiphere/$OCApacheip/g" /var/www/opencart/admin/config.php
- /bin/sed -i "s/dbiphere/$MySQLip/g" /var/www/opencart/admin/config.php
- /bin/sed -i "s/usernamehere/$USER/g" /var/www/opencart/admin/config.php
- /bin/sed -i "s/passwordhere/$PASS/g" /var/www/opencart/admin/config.php
- /bin/systemctl reload apache2
- /bin/systemctl restart apache2
- cd /tmp
- /bin/echo "ocuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
- /bin/echo 'Cloud-init is done!' >> /tmp/finished.txt
- /bin/echo "END END END END END END END END END"
- /bin/echo "END END END END END END END END END"
#
#
packages:
  - apache2
  - php
  - php-mysql
  - libapache2-mod-php
  - php-cli
  - php-common
  - php-intl
  - php-gd
  - php-mbstring
  - php-xml
  - php-zip
  - php-curl
  - php-xmlrpc
  - mysql-server-5.7
  - unzip
  - open-vm-tools
#
#
timezone: America/Chicago
#
#
system_info:
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
disable_root: false
ssh_pwauth: yes  
users:
  - default
  - name: cloudadmin
    gecos: Cloud
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
  - name: ocuser
    gecos: Opencart User
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    default-user: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0
    ocuser: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0 
    cloudadmin: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0
  expire: false
package_upgrade: true
package_reboot_if_required: true
power_state:
  delay: now
  mode: reboot
  message: Rebooting the OS
  condition: if [ -e /var/run/reboot-required ]; then exit 0; else exit 1; fi
